### ISSUE TITLE
[IDEA]: Use a unique oauth redirect_uri

### ISSUE THREAD

**Issue by iOvergaard** [umbraco/Umbraco.CMS.Backoffice#1165]
When doing an authorization request against an oauth provider, e.g. the Umbraco instance, we set the redirect_uri to a root address, i.e. `/`. When the authorization request returns from the provider carrying the PKCE code, we need to catch it before anything else happens in the routing system. This is done in the main `#redirect` method in UmbAppElement. It is a very simplistic check to see if there is a parameter called `code` in the URL search parameters and is therefore prone to failure if anything else should use this.

What you usually do according to industry-wide standards is to have a dedicated route to catch the authorization return. This is how Postman and the Swagger UI are set up for instance. To do this, we need to calculate the base path of the backoffice and append the route to it before sending the authorization request. The route could be something like `/oauth_complete`.

We would have to set it up in or around the `redirect_uri` parameter in the authorization request:

https://github.com/umbraco/Umbraco.CMS.Backoffice/blob/d558562aec97b7ce886d4869ce8df434bc78a334/src/shared/auth/auth-flow.ts#L202-L213

And also in the token request:

https://github.com/umbraco/Umbraco.CMS.Backoffice/blob/d558562aec97b7ce886d4869ce8df434bc78a334/src/shared/auth/auth-flow.ts#L298-L305

Lastly, we would have to set up a new route for this and call `UmbAuthContext#completeAuthorizationRequest` method in the router's `resolve` callback:

https://github.com/umbraco/Umbraco.CMS.Backoffice/blob/d558562aec97b7ce886d4869ce8df434bc78a334/src/apps/app/app.element.ts#L41-L56

The route should be ignored in the main router initialization method called `#redirect` just like `/install` and `/upgrade` already are:

https://github.com/umbraco/Umbraco.CMS.Backoffice/blob/d558562aec97b7ce886d4869ce8df434bc78a334/src/apps/app/app.element.ts#L164-L177

(It wouldn't hurt to replace this with a more programmatic approach where you are sure the routes and redirects follow each other)

The route that the user initially had is stored in the session storage and will be restored in the authorization notifier automatically, so we don't have to worry about that:

https://github.com/umbraco/Umbraco.CMS.Backoffice/blob/d558562aec97b7ce886d4869ce8df434bc78a334/src/shared/auth/auth-flow.ts#L147-L152
```[tasklist]
### Tasks
- [ ] Add new route
- [ ] Call complete authorization in the resolve callback
- [ ] Calculate the appropriate redirect_uri based on the <base> element
- [ ] Update authentication.md to describe what to set in appsettings.json
- [ ] Update the authentication configuration on the server to automatically use the new /oauth_complete route
```
