### ISSUE TITLE
Property Editor: Textarea

### ISSUE THREAD

**Issue by iOvergaard** [umbraco/Umbraco.CMS.Backoffice#456]
```[tasklist]
### Tasks
- [x] Property editor scaffolding
- [ ] https://github.com/umbraco/Umbraco.CMS.Backoffice/issues/457
- [ ] https://github.com/umbraco/Umbraco.CMS.Backoffice/issues/458
- [ ] https://github.com/umbraco/Umbraco.CMS.Backoffice/issues/459
```
